---
title: "Tidy Tuesday 01-16"
author: "Rahim Jutha"
date: "2023-01-17"
output: html_document
---

# Introduction
https://github.com/rfordatascience/tidytuesday/blob/master/data/2023/2023-01-10/readme.md

# Download the data

Code from tidy tuesday post to download, then subset, and finally  write the data to a csv file.
```{r, eval=FALSE}
# Download the raw data.

PFW_2021_public <- readr::read_csv("https://clo-pfw-prod.s3.us-west-2.amazonaws.com/data/PFW_2021_public.csv")
dplyr::glimpse(PFW_2021_public)

# There are almost three million rows! The file is too big for github, let's
# subsample.

set.seed(424242)
PFW_2021_public_subset <- dplyr::slice_sample(PFW_2021_public, n = 1e5)

readr::write_csv(PFW_2021_public_subset, "data/PFW_2021_public.csv")
```

# Read in Data

```{r}
library(tidyverse)
library(magrittr)
library(skimr)
library(rnaturalearth)
library(rnaturalearthdata)
library(cowplot)
library(janitor)
library(ggimage)
library(ggtext)
library(showtext)

data <- read_csv("data/PFW_2021_public.csv")
skim(data)
```

# EDA

```{r}

map <- ne_countries(scale = "medium", returnclass = "sf") %>%
  filter(name %in% c("Canada", "United States"))

# ggplot() +
#   geom_sf(data = map) +
#   geom_point(aes(x = longitude, y = latitude), data = data, alpha = .2)

data %>% filter(latitude < 22)

data %>%
  filter(latitude > 22) %>%
ggplot() +
  geom_sf(data = map, fill = "grey95", color = "grey40") +
  geom_point(aes(x = longitude, y = latitude), alpha = .2) +
  coord_sf(
    xlim = c(-175,-55),
    ylim = c(25,85)) + 
  labs(
    x = NULL,
    y = NULL
  ) +
  theme_minimal() +
  theme(
    panel.grid = element_blank(),
    panel.background  = element_blank(),
    axis.text.x = element_blank(),
    axis.text.y = element_blank()
  )
```

# Most common birds in BC
Using https://github.com/michael-millett/tidy-tuesday/tree/main/2023/Week%202%20-%20FeederWatch%20Birds as a guide.

```{r, fig.showtext=TRUE}
bc_birds <-
  data %>%
  filter(subnational1_code == "CA-BC") %>%
  filter(valid == 1) %>%
  select(species_code, how_many)

# Import species codebook to join their names with species code in df
# (downloaded from FeederWatch dictionary codebook)
bird_names <- read_csv("data/species_codes.csv", skip = 1) %>%
  clean_names() %>%
  select(species_code, primary_com_name)

bc_birds %<>%
  left_join(., bird_names, by = "species_code")

rm(bird_names)

bc_birds %<>%
  rename(bird_name = primary_com_name) %>%
  group_by(bird_name) %>%
  summarize(
    total_spotted = sum(how_many)
  ) %>%
  arrange(desc(total_spotted)
          ) %>%
  mutate(bird_name = as_factor(bird_name),
         bird_name = fct_reorder(bird_name, total_spotted))

# Pick Fonts
font_add_google("Oswald", family = "Oswald")
font_add_google("Roboto", family = "Roboto")
font_add_google("Assistant", family = "Assistant")
showtext_auto()
showtext_opts(dpi=300) 

f1 <- "Oswald"
f2 <- "Roboto"
f3 <- "Assistant"

# Make the barplot
plot <- ggplot(data = head(bc_birds, 10),
               aes(x = bird_name,
                   y = total_spotted)) +
  geom_col(fill = "#0f4c81",
           alpha = 0.8) +
  scale_y_continuous(
    limits = c(0,2500),
    breaks = seq(0,2000,500),
    minor_breaks = NULL,
    position = "right"
  ) +
  coord_flip(clip = "off") +
  labs(
    x = NULL,
    y = NULL,
    title = "Most Common Birds Sighted in BC",
    subtitle = "Sightings Reported from Project FeederWatch Members (Nov 2020 - Apr 2021)",
    caption = "Source: Project FeederWatch (Subsetted Data) | Graphic by Rahim Jutha"
  )
  
# Add themes
plot <- plot + theme(
  plot.margin = margin(c(20,40,30,20)),
  panel.background = element_rect(fill = "grey90", linewidth = 0),
  plot.background = element_rect(fill = "grey90", linewidth = 0),
  panel.grid.major.y = element_blank(),
  panel.grid.major.x = element_line(color = "grey78", linewidth = 0.5),
  axis.ticks.x = element_line(color = "grey78", size = 0.5),
  axis.ticks.y = element_blank(),
  plot.title.position = "plot",
  plot.title = element_text(size = 32, family = f1, 
                            hjust = 0.5, 
                            margin = margin(2, 2, 2, 2)),
  plot.subtitle = element_text(size = 18, family = f2, 
                               color = "grey40", 
                               hjust = 0.5,
                               vjust = -1,
                               margin = margin(2, 2, 20, 2)),
  axis.text.x = element_text(size = 17, family = f3,
                             ),
  axis.text.y = element_text(size = 16, family = f3,
                             margin = margin(0, -15, 0, 0)),
  plot.caption = element_text(size = 15, family = f3,
                              vjust = -4, hjust = 0, color = "grey20")
)

plot <- plot +
  geom_image(aes(x = 9.75, y = 2400, image = "pictures/pinesiskin.png"), size = 0.2) +
  geom_image(aes(x = 7.625, y = 2400, image = "pictures/dark-eyedjunco.png"), size = 0.2) +
  geom_image(aes(x = 5.5, y = 2400, image = "pictures/bushtit.png"), size = 0.2) +
  geom_image(aes(x = 3.375, y = 2400, image = "pictures/black-cappedchickadee.png"), size = 0.2) +
  geom_image(aes(x = 1.25, y = 2400, image = "pictures/californiaquail.png"), size = 0.2) +
  annotate("label",
           x = 8.75,
           y = 2400,
           size = 4.5,
           label = "Pine Siskin",
           family = f3,
           color = "grey20",
           fill = "grey90") +
  annotate("label",
           x = 6.625,
           y = 2400,
           size = 4.5,
           label = "Dark-eyed Junco",
           family = f3,
           color = "grey20",
           fill = "grey90") +
  annotate("label",
           x = 4.5,
           y = 2400,
           size = 4.5,
           label = "Bushtit",
           family = f3,
           color = "grey20",
           fill = "grey90") +
  annotate("label",
           x = 2.375,
           y = 2400,
           size = 4.5,
           label = "Black-capped Chickadee",
           family = f3,
           color = "grey20",
           fill = "grey90") +
  annotate("label",
           x = 0.25,
           y = 2400,
           size = 4.5,
           label = "California Quail",
           family = f3,
           color = "grey20",
           fill = "grey90")

plot
ggsave("bc_birds.png", plot = plot, width = 10, height = 7.5)
```

# To get all the BC Bird data

Should've used this from the start but instead of the subsetted data.

```{r, eval=FALSE}
PFW_2021_public <- readr::read_csv("https://clo-pfw-prod.s3.us-west-2.amazonaws.com/data/PFW_2021_public.csv")

bc_birds_full <-
  PFW_2021_public %>%
  filter(subnational1_code == "CA-BC") %>%
  filter(valid == 1) %>%
  select(species_code, how_many)

# Import species codebook to join their names with species code in df
# (downloaded from FeederWatch dictionary codebook)
bird_names <- read_csv("data/species_codes.csv", skip = 1) %>%
  clean_names() %>%
  select(species_code, primary_com_name)

bc_birds_full %<>%
  left_join(., bird_names, by = "species_code")

rm(bird_names)

bc_birds_full %<>%
  rename(bird_name = primary_com_name) %>%
  group_by(bird_name) %>%
  summarize(
    total_spotted = sum(how_many)
  ) %>%
  arrange(desc(total_spotted)
          ) %>%
  mutate(bird_name = as_factor(bird_name),
         bird_name = fct_reorder(bird_name, total_spotted))
  
```