---
title: "eda"
format: html
editor: visual
---

## Load Packages

```{r}
library(tidyverse)
library(janitor)
```

## Load Data

```{r}
raw_data <- readr::read_csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2023/2023-08-15/spam.csv') %>%
  clean_names()
```

```{r}
raw_data %>%
  glimpse()
```

## Plot of the distribution of all variables

```{r}
plot_data <- raw_data %>%
  pivot_longer(cols = 1:6, names_to = 'variable', values_to = 'value') %>%
  mutate(
    yesno = case_when(
      yesno == 'y' ~ 'Yes',
      yesno == 'n' ~ 'No'
    ),
    description = case_when(
      variable == 'crl_tot' ~ 'Total length of uninterrupted sequences of capitals',
      variable == 'dollar' ~ 'Occurrences of the dollar sign, as percent of total number of characters',
      variable == 'bang' ~ 'Occurrences of ‘!’, as percent of total number of characters',
      variable == 'money' ~ 'Occurrences of ‘money’, as percent of total number of characters',
      variable == 'n000' ~ 'Occurrences of the string ‘000’, as percent of total number of words',
      variable == 'make' ~ 'Occurrences of ‘make’, as a percent of total number of words'
    )
  )
```

```{r}
plot_data %>%
  ggplot() +
  geom_boxplot(aes(x = (value), y = yesno, fill = yesno)) +
  facet_wrap(~description, scales = 'free') +
  scale_x_log10()
  theme_minimal()
  
  plot_data %>%
  ggplot() +
  geom_boxplot(aes(x = (value), y = yesno, fill = yesno)) +
  facet_wrap(~description, scales = 'free') +
  theme_minimal()
```

```{r}
library(brms)

mod_data <- raw_data %>%
  mutate(
    yesno = case_when(
      yesno == 'y' ~ 1,
      yesno == 'n' ~ 0,
    )
  )

mod <- brm(yesno ~ ., data = mod_data)
summary(mod)
```

```{r}
# https://archive.ics.uci.edu/dataset/94/spambase
spam_text <- 'aaa'

n_char <- str_length(spam_text)
n_word <- str_count(spam_text, '[\\d\\w]+')

# Total number of capital letters
crl_tot <- str_count(spam_text, '[A-Z]')

# All occurrences of $
dollar <- str_count(spam_text, '\\$') / n_char * 100

# all occurrences of !
bang <- str_count(spam_text, '!') / n_char * 100

# All occurrences of money (lowered to deal with cases like MoNeY)
money <- str_count(str_to_lower(spam_text), 'money') / n_word * 100

# All occurrences of 000
n000 <- str_count(spam_text, '000') / n_word * 100

# All occurences of make 
make <- str_count(str_to_lower(spam_text), 'make') / n_word * 100
```

```{r}
df_new_spam <- tibble(dollar = dollar, bang = bang, money = money, n000 = n000, make = make, crl_tot = crl_tot)

pred <- posterior_predict(mod, newdata = df_new_spam)[,1]
pred <- exp(pred)/(1+exp(pred))

ggplot() +
  geom_histogram(aes(x =pred), bins = 150) +
  scale_x_continuous(breaks = c(0,0.25,.5,.75,1))

mean(pred)
```